platform :ios,’8.0’


target ‘EVNEstorePlatform’ do

pod 'MBProgressHUD', '~> 1.0.0'
pod 'FMDB'

pod 'SDWebImage'
pod 'IQKeyboardManager', '~> 3.3.7'

pod 'MJRefresh'
pod 'MJExtension'

pod 'MWPhotoBrowser'

pod 'AFNetworking', '~> 3.0'

end
